version: '3.9'

services:

  database:
    container_name: postgres
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  axlip:
    container_name: axlip
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TG_TOKEN=${TG_TOKEN}

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"